add_newline = false

format = """
$os\
$username\
[ ](bg:black fg:white)\
${custom.path_icon}\
$directory\
$git_branch\
$git_status\
$docker_context\
${custom.language_line}\
$time\
$line_break$character
"""

right_format = """
$cmd_duration\
"""

[os]
disabled = false
style = "bg:black fg:white"

[os.symbols]
Windows = " 󰍲 "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[✗](bold red)'

[directory]
style = "bold bg:black fg:blue"
format = "[$path ]($style)"
truncation_length = 10
truncate_to_repo = false

[custom.path_icon]
command = """
if [ "$PWD" = "$HOME" ]; then
    echo ''
else
    echo ''
fi
"""
when = "true"
style = "bg:black fg:white"

[git_branch]
symbol = ""
style = "bold bg:black fg:purple"
format = '[[](bg:black fg:white) $symbol$branch ]($style)'

[git_status]
style = "bold bg:black fg:purple"
format = '([\[$all_status$ahead_behind\] ]($style))'

[docker_context]
symbol = ""
style = "bold bg:black fg:bright-blue"
format = '[[](bg:black fg:white) $symbol($context) ]($style)'

[custom.language_line]
command = """
output="\n"
if [ -n "$(ls *.java 2>/dev/null)" ] || [ -f "pom.xml" ] || [ -f "build.gradle" ]; then
    output+=$(starship module java)
fi
if [ -n "$(ls *.py 2>/dev/null)" ] || [ -f "requirements.txt" ] || [ -f "setup.py" ]; then
    output+=$(starship module python)
fi
if [ -n "$(ls *.php 2>/dev/null)" ] || [ -f "composer.json" ]; then
    output+=$(starship module php)
fi
if [ -n "$output" ]; then
    echo -e "$output"
fi
"""
when = "true"
style = "fg:black"

[java]
symbol = ""
format = '[$symbol$version](bold bright-red) '

[python]
symbol = ""
format = '[$symbol$version](bright-cyan) '

[php]
symbol = ""
format = '[$symbol$version](bright-purple) '

[cmd_duration]
min_time = 100
show_milliseconds = true
style = 'bg:black fg:yellow'
format = '[](fg:black)[ $duration]($style)'
