#fish
add_newline = false

format = """
$os\
$username\
[ ](bg:black fg:white)\
${custom.path_icon}\
$directory\
$git_branch\
$git_status\
$docker_context\
${custom.language_line}\
$time\
$line_break$character
"""

right_format = """
$cmd_duration\
"""

[os]
disabled = false
style = "bg:black fg:white"

[username]
style_user = "bold bg:black fg:bright-yellow"
style_root = "bold bg:black fg:bright-red"
format = "[$user ]($style)"

[os.symbols]
Windows = " 󰍲 "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[✗](bold red)'

[directory]
style = "bold bg:black fg:blue"
format = "[$path ]($style)"
truncation_length = 10
truncate_to_repo = false

[custom.path_icon]
command = """
if test "$PWD" = "$HOME"
    echo ''
else
    echo ''
end
"""
when = "true"
style = "bg:black fg:white"

[git_branch]
symbol = ""
style = "bold bg:black fg:purple"
format = '[[](bg:black fg:white) $symbol$branch ]($style)'

[git_status]
style = "bold bg:black fg:purple"
format = '([\[$all_status$ahead_behind\] ]($style))'

[docker_context]
symbol = ""
style = "bold bg:black fg:bright-blue"
format = '[[](bg:black fg:white) $symbol($context) ]($style)'

[custom.language_line]
command = """
set output "\n"
if test (ls *.java 2>/dev/null | wc -l) -gt 0 -o -f "pom.xml" -o -f "build.gradle"
    set output $output (starship module java)
end
if test (ls *.py 2>/dev/null | wc -l) -gt 0 -o -f "requirements.txt" -o -f "setup.py"
    set output $output (starship module python)
end
if test (ls *.php 2>/dev/null | wc -l) -gt 0 -o -f "composer.json"
    set output $output (starship module php)
end
if test (ls *.js 2>/dev/null | wc -l) -gt 0 -o -f "package.json"
    set output $output (starship module nodejs)
end
if test -n "$output"
    echo "$output"
end
"""
when = "true"
style = "fg:black"

[java]
symbol = ""
format = '[$symbol$version](bold bright-red) '

[python]
symbol = ""
format = '[$symbol$version](bright-cyan) '

[php]
symbol = ""
format = '[$symbol$version](bright-purple) '

[nodejs]
symbol = ""
format = '[$symbol$version](bold bright-green) '

[cmd_duration]
min_time = 100
show_milliseconds = true
style = 'bold bg:black fg:bright-yellow'
format = '[](fg:black)[ $duration]($style)'
