add_newline = false

format = """$os$username[ ](fg:white)$directory$git_branch$git_status$docker_context$time$line_break$character"""

right_format = """$cmd_duration"""

[os]
disabled = false
style = "fg:white"

[os.symbols]
Windows = " 󰍲 "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[✗](bold red)'

[directory]
style = "bold fg:blue"
format = "[$path ]($style)"
truncation_length = 10
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bold fg:purple"
format = '[[](fg:white) $symbol$branch]($style)'

[git_status]
style = "bold fg:purple"
format = '([\[$all_status$ahead_behind\] ]($style))'

[docker_context]
symbol = ""
style = "bold fg:bright-blue"
format = '[[](fg:white) $symbol($context) ]($style)'

[cmd_duration]
min_time = 100
show_milliseconds = true
style = 'bg:black fg:yellow'
format = '[](fg:black)[ $duration]($style)'
